[mypy]
python_version = 3.12
strict = false
warn_return_any = false
warn_unused_configs = true
ignore_missing_imports = true
exclude = (tests|docs)/
disable_error_code = union-attr, index, call-arg, attr-defined
